### ISSUE TITLE
Hi guys, how to setup more roles?

### ISSUE THREAD

**Issue by minhvn** [l1br3/sails-role-permissions#1]
Please help me, I have Account Model and using session to auth, how to setup it with this module?
Have more 3 roles, please help me :)
Thank you very much.
Minh.

**Comment by l1br3** [comment]
Hi, you need a roles property in your config. Usually a file named roles.js in config dir.
Then you put this content: 
```javascript
module.exports = [
'admin', // Keep this one
'yourFirstRole',
'anotherRole'
]
```

Your auth policy must be called for any route you need to use the module and you must set the req.user.role attribute too.

Then, everything should be working.

**Comment by minhvn** [comment]
Thank you very much,
But, when I merge My Account Model( I dont have User model) with User model it show error ORM.
I see your hook permission using fix User name of model, it effect my config? Please help me, I take 2days for fix it but cannot run :(
Thank you very much.

**Comment by l1br3** [comment]
Sorry, I don't understand what you mean by merging your Account model and User model.
You don't need a User model at all with this module. But you must set a property user to req in your authentication policy.

An exemple of mine
```javascript
const passport = require('passport');

module.exports = (req, res, next) => {

  if(!req.headers.authorization) return next()

  passport.authenticate('jwt', (error, user, info) => {

    if(user) req.user = user
    next()

  })(req, res)
};
```
This hook does not mess with Models. Could you elaborate on the following sentence please ? 
*I see your hook permission using fix User name of model*

**Comment by l1br3** [comment]
I strongly suggest you to start from a clean sails install to understand how the hook works, then you will be ale to integrate it in your current project.

**Comment by minhvn** [comment]
Sorry, I mistake,
I only want ask, we must add field role to user account?
You can give me skype or... I need some help for sails permission...
Thank you very much.
Minh

**Comment by minhvn** [comment]
And, you have sample using it? thank you thank you...

**Comment by l1br3** [comment]
You don't need to set up anything expect having a config file, everything is explained in the readme.

- install a new sails app
- install the hook
- create a policy which set req.user.role to your session during authentication
- create a config file

That's all, you don't need anything more.

**Comment by minhvn** [comment]
Thank you,
I config:
1. npm install --save sails-role-permissions

2. Create config/role.js
`module.exports = [
    'admin',
    'student',
    'partner',
    'editor'
]
`
3. Create config/permissions.js 
`module.exports.permissions = {
    debug : {
        message : true,
        stack : true,
        filters : true
    },

    account : {
        destroy : 'admin',
        find : {
            email : 'private' 
        },
        create : {
            '*' : 'guest' 
        },
        update : {}, 
        populate : {
        }
      processing (even if your action in your controller is in camelCase)
    }
}`

4. Set role in user session:
`req.session.user.role = account.type;`

Anything above ok? 
Thank you very much.

**Comment by l1br3** [comment]
The user must be directly on the req.
`req.user.role` instead of `req.session.user.role`

**Comment by minhvn** [comment]
Thank you for support time,
"create a policy which set req.user.role to your session during authentication" => no need store on session?
req.user.role -> assign when request from frontend? 
I only set when login successful req.user.role = account.type.
Thank you very much.
Minh

**Comment by l1br3** [comment]
I don't remember how sails handle sessions, I use now a JWT and each request gets authenticated. 
You MUST store the role on user object as req.user.role. It is necessary.

**Comment by minhvn** [comment]
Thank you,
After config, i using node app and it hav error
error: A hook (`userconfig`) failed to load!

**Comment by l1br3** [comment]
This has nothing to do with the module itself, I'm going to make an exemple repo so you can start from here

**Comment by l1br3** [comment]
The repo is done, the hook has been updated due to a bug with camelCased controllers/actions.
Everything should be now straight forward, I cannot help more.
https://github.com/l1br3/sails-role-permissions-test-repo

**Comment by minhvn** [comment]
Thank you very much, I check it right now,  I see it error because role.js export to array.
error: Error: When using `aggregate`, modules must export dictionaries.  But module (`role`) is invalid:admin,student,partner,editor
:(

**Comment by l1br3** [comment]
Look at the example repo, I made a mistake here, the roles array must be part of permissions object.
Please look at this repo

**Comment by l1br3** [comment]
I set up more role in the repo, now I consider this issue closed.

**Comment by minhvn** [comment]
I have some error :   "message": "_RoleUtil2.default is not a constructor” :(
Thank you, sorry for my issue….

**Comment by l1br3** [comment]
Do you have this error on the example repo ?

**Comment by l1br3** [comment]
Provide an exemple repo with the error mentioned above.

**Comment by l1br3** [comment]
Just tried to clone the exemple repo and everything is working as expected. I don't know what are you doing but it might be an issue on your side :)

**Comment by minhvn** [comment]
Hi guys,
I download your example, run and goto url :1337/video and it show:
```TypeError: _RoleUtil2.default is not a constructor
    at controllersPolicy.configRoleUtil (/Users/MinhVN/Downloads/sails-role-permissions-test-repo-master/node_modules/sails-role-permissions/lib/policies/policyMethods.js:54:23)
```
My project integrate the same error, if you can please help me check, add skype will provide you teamviewer, please help me, I take many time for this case....

**Comment by l1br3** [comment]
`"Error: Action Error video::find (controller::action) : action is set to false`

The message is quite clear, if you had looked 2 seconds at the config you would have see that anything is denied to 'GET /video' because permissions.video.find is set to false, as the message says.

I'm sorry but I'm not here to bug track stuff on your side, you have a huuuuge readme and examples, I cannot do more.

**Comment by minhvn** [comment]
Hic hic, thank you.
We need config policies vs permissions? I see example config two 2 :)

**Comment by l1br3** [comment]
I don't understand your question.

**Comment by minhvn** [comment]
Hi, no solve, I must goto sleep, here is 1:32 AM :((
Will continue to morrow….
Thank you for support, very very thank you spend time for my issue :)
