### ISSUE TITLE
Found my problem

### ISSUE THREAD

**Issue by minhvn** [l1br3/sails-role-permissions#2]
When install from npm, in sails-role-permissions/lib/util/ have 2 file RoleUtil.js and roleUtil.js -> it happen my error.

**Comment by l1br3** [comment]
Thanks for the report, I publish a new version right now

**Comment by Fr33maan** [comment]
https://github.com/l1br3/sails-role-permissions/commit/c7046c29f070cb7d95bf53cc91ed250763cdd164 fixes this bug. New version on npm
