### ISSUE TITLE
Order Role permission

### ISSUE THREAD

**Issue by minhvn** [l1br3/sails-role-permissions#3]
Hi guys,
Role permission by order? 
I see role array, if role A above role B, will cover permission of role B?
I have two role, student and partner, can I config it student not cover partner and partner not cover student...
Thank you very much.

**Comment by l1br3** [comment]
Hi @minhvn, as you said, roles are ordered. If role A is above role B, A can access all B policies but B cannot access A policies.

For what you want to do you must use classic sails policies. Something like `isStudent` or `isPartner` to apply on controllers/actions.

**Comment by minhvn** [comment]
Hic, as you said, we must using both classic and sails-role-permission in project? anything else for do with sails-role-permissions?
Thank you,

**Comment by Fr33maan** [comment]
I don't know what is your use case. If your role exclude each other then you should use classic policies for thoses controllers/actions and not sails-role-permissions as it uses role hierarchy.

**Comment by minhvn** [comment]
Thank you, I will check my project again 👍 thank for your time :) You have skype?
